name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Deploy to GCP VM via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ 34.27.198.245 }}
        username: ${{ wafiqmariatula }}
        key: ${{ secrets.GCP_VM_SSH_PRIVATE_KEY }}
        script: |
          cd /home/wafiqmariatula
          git pull origin main
          sudo systemctl restart flask-app
